<?php

/**
 * @file
 * Display Suite core functions.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\view_modes_inventory\ViewModesInventoryFactory;

/**
 * Implements hook_help().
 */
function view_modes_inventory_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.view_modes_inventory':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<br/>' . t('The <a href="https://www.drupal.org/project/view_modes_inventory">View modes inventory</a> module has a set of template view modes that we typically use (some of them) in each website.');
      return $output;
  }
}

/**
 * Implements hook_form_alter().
 */
function view_modes_inventory_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state) {

  // Apply the config for view modes inventory form entity view display.
  $form['actions']['submit']['#submit'][]  = '_view_modes_inventory_form_entity_view_display_edit_form_submit';
}

/**
 * Apply mapped view modes inventory form entity view display edit form submit.
 */
function _view_modes_inventory_form_entity_view_display_edit_form_submit($form, FormStateInterface $form_state) {

  if (isset($form['modes']['display_modes_custom'])) {

    // Entity type.
    $entity_type = $form['#entity_type'];

    // Bundle name.
    $bundle_name = $form['#bundle'];

    // View modes inventory list.
    $view_modes_inventory_list = ViewModesInventoryFactory::getViewModesList();

    // View modes inventory layouts mapping.
    $view_modes_inventory_layouts_mapping = ViewModesInventoryFactory::getLayoutsMapping();

    // Available view modes for content types.
    $available_view_modes = $form['modes']['display_modes_custom']['#options'];

    // Enabled view modes.
    $enabled_view_modes = $form['modes']['display_modes_custom']['#default_value'];

    // Current selected view modes.
    $selected_view_modes = $form['modes']['display_modes_custom']['#value'];

    if (isset($view_modes_inventory_list['view_modes'])
        && isset($view_modes_inventory_layouts_mapping['mapping'])) {

      foreach ($selected_view_modes as $selected_view_mode) {
        // Only when we do hava a new selected view mode inventory.
        if (!isset($enabled_view_modes[$selected_view_mode])
           && isset($view_modes_inventory_list['view_modes'][$selected_view_mode])
           && isset($view_modes_inventory_layouts_mapping['mapping'][$selected_view_mode])
           && isset($view_modes_inventory_layouts_mapping['mapping'][$selected_view_mode]['layout'])
           && isset($view_modes_inventory_layouts_mapping['mapping'][$selected_view_mode]['config_template'])
           && isset($view_modes_inventory_layouts_mapping['mapping'][$selected_view_mode]['config_name'])) {

          $default_mapped_layout = $view_modes_inventory_layouts_mapping['mapping'][$selected_view_mode]['layout'];
          $config_template_file = $view_modes_inventory_layouts_mapping['mapping'][$selected_view_mode]['config_template'];
          $config_name = $view_modes_inventory_layouts_mapping['mapping'][$selected_view_mode]['config_name'];

          ViewModesInventoryFactory::mapViewModeWithLayout($selected_view_mode, $default_mapped_layout, $entity_type, $bundle_name, $config_template_file, $config_name);

        }
      }
    }
  }
}
